### ISSUE TITLE
Homebridge won't run

### ISSUE THREAD

**Issue by PolarHacker** [topas/homebridge-rfbuttons#5]
Okay, I tried to install RFButtons manually as it seemed NPM wasn't working. I think I'm on to something, but I get this error when trying to run Homebridge:

`[RFButtons] Initializing RFButtons platform...
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at new Sniffer (/usr/lib/node_modules/homebridge-rfbuttons/node_modules/rpi-433/Sniffer.js:22:21)
    at Function.Sniffer.getInstance (/usr/lib/node_modules/homebridge-rfbuttons/node_modules/rpi-433/Sniffer.js:49:50)
    at Object.sniffer (/usr/lib/node_modules/homebridge-rfbuttons/node_modules/rpi-433/index.js:23:20)
    at new RFButtonsPlatform (/usr/lib/node_modules/homebridge-rfbuttons/index.js:17:29)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:304:32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
`

Any suggestions? :)

**Comment by topas** [comment]
Sorry, this project is no longer being maintained. I don't have time for it. I'll keep this repo for inspiration.
